version: '3.8'

services:
  terrabia:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${RENDER_POSTGRES_HOST}:${RENDER_POSTGRES_PORT}/${RENDER_POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${RENDER_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${RENDER_POSTGRES_PASSWORD}
